spring:
  application:
    name: rabbitmq.producer

  rabbitmq:
    addresses: "localhost:5672"
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true