spring:
  application:
    name: rabbitmq.consumer

  rabbitmq:
    addresses: "localhost:5672"
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1 # default prefetch value is 250; this should be lowered when we have slow consumers